import { definePage } from '../../lib/guide-types';
import { P, FI, EN } from '../../lib/fmt';
import { laskeVerot } from '../../lib/engine/vero';

const M = P.vero.matkakulut;
const ESITYS = P.kotitalousvahennys.esitys_matkakulut_omavastuu;
const PALKKA = 42000;
const PV = 220;
const kulut = (km: number) => km * 2 * PV * M.oma_auto_euroa_km;
const vahennys = (k: number) => Math.min(M.enimmaismaara, Math.max(0, k - M.omavastuu));
const sasto = (k: number, tulo = PALKKA) => laskeVerot({ tulo }).verot - laskeVerot({ tulo, matkakulut: k }).verot;

const KM = 25;
const K25 = kulut(KM);
const S25 = sasto(K25);
const ILMAN = laskeVerot({ tulo: PALKKA });
const KANSSA = laskeVerot({ tulo: PALKKA, matkakulut: K25 });
// Kilometrit, joilla omavastuu ylittyy ja enimmäisvähennys täyttyy (yhteen suuntaan, PV työpäivää).
const KM_ALKAA = M.omavastuu / M.oma_auto_euroa_km / (2 * PV);
const KM_KATTO = (M.enimmaismaara + M.omavastuu) / M.oma_auto_euroa_km / (2 * PV);
const LIPPU = 60 * 11;
const ESITYS_LISA = sasto(K25 + (M.omavastuu - ESITYS)) - S25;
const MATKAT = [10, 25, 40, 60, 80].map((km) => ({ km, k: kulut(km), v: vahennys(kulut(km)), s: sasto(kulut(km)) }));
const PV_HYB = Math.round(PV * 3 / 5);
const K_HYB = KM * 2 * PV_HYB * M.oma_auto_euroa_km;
const S_HYB = sasto(K_HYB);
const S25_PIENI = sasto(K25, 25000), S25_SUURI = sasto(K25, 60000);

export default definePage({
  id: 'matkakulut',
  group: 'vero',
  order: 110,
  mini: 'matka',
  related: ['verolaskuri', 'veronpalautus', 'kotitalousvahennys-laskuri', 'veroprosenttilaskuri'],
  sources: ['vero_ennakonpidatys', 'vero_kotitalous_esitys'],
  fi: {
    slug: 'matkakulujen-verovahennys',
    nav: 'Matkakulujen vähennys',
    card: 'Työmatkakulujen verovähennys 2026: omavastuu, enimmäismäärä, kilometrikorvaus omalla autolla ja veron säästö.',
    title: `Matkakulujen verovähennys 2026: omavastuu ${FI.eur(M.omavastuu)}, ${FI.eur(M.oma_auto_euroa_km, 2)}/km`,
    description: `Matkakulujen vähennys 2026: asunnon ja työpaikan välisistä kuluista vähennetään ${FI.eur(M.omavastuu)} omavastuun ylittävä osa, enintään ${FI.eur(M.enimmaismaara)}. Laske oma veron säästösi.`,
    h1: 'Työmatkakulujen verovähennys',
    intro: 'Asunnon ja työpaikan väliset matkat ovat vähennyskelpoisia, kun ne maksavat vuodessa enemmän kuin omavastuu.',
    resume: `Asunnon ja työpaikan välisten matkojen kuluista saa vuonna 2026 vähentää sen osan, joka ylittää ${FI.eur(M.omavastuu)} omavastuun, enintään ${FI.eur(M.enimmaismaara)} vuodessa. Vähennys lasketaan halvimman käytettävissä olevan kulkuneuvon mukaan; kun oman auton käyttö on hyväksyttävää, kulut lasketaan ${FI.eur(M.oma_auto_euroa_km, 2)} kilometriltä. Esimerkiksi ${KM} kilometrin työmatka yhteen suuntaan ${PV} työpäivänä tekee omalla autolla ${FI.eur(K25)} kuluja, joista vähennyskelpoista on ${FI.eur(vahennys(K25))}. ${FI.eur(PALKKA)} vuosipalkalla Helsingissä vähennys pienentää veroja ${FI.eur(S25)}. Säästö on suurempi kuin pelkkä kunnallisveron osuus, koska vähennys pienentää puhdasta ansiotuloa ja sen myötä valtionveroa, sairaanhoitomaksua ja Yle-veroa. Hallitus on esittänyt omavastuun laskemista ${FI.eur(ESITYS)} euroon, mutta esitystä ei ole hyväksytty, joten tällä sivulla lasketaan voimassa olevalla ${FI.eur(M.omavastuu)} omavastuulla. Vähennyksen voi ottaa huomioon jo verokortissa tai vasta veroilmoituksella, jolloin hyöty tulee veronpalautuksena. Etätyöpäivät, lomat ja sairauspoissaolot eivät ole työmatkapäiviä.`,
    faqs: [
      { q: 'Kuinka pitkä työmatkan pitää olla, että matkakuluja voi vähentää?', a: `Omalla autolla laskettuna omavastuu ${FI.eur(M.omavastuu)} ylittyy noin ${FI.num(KM_ALKAA, 1)} kilometrin matkalla yhteen suuntaan, kun työpäiviä on ${PV}. Laskelma pätee kuitenkin vain, jos oman auton käyttö hyväksytään; muuten vähennys lasketaan julkisen liikenteen hinnasta, ja silloin raja ylittyy vasta, kun lippuihin kuluu yli ${FI.eur(M.omavastuu)} vuodessa.` },
      { q: 'Paljonko 25 kilometrin työmatka säästää veroja?', a: `${KM} kilometrin matka yhteen suuntaan ${PV} päivänä on omalla autolla ${FI.eur(K25)} vuodessa. Omavastuun jälkeen vähennys on ${FI.eur(vahennys(K25))}. ${FI.eur(PALKKA)} palkalla Helsingissä verot pienenevät ${FI.eur(S25)}, ${FI.eur(25000)} palkalla vain ${FI.eur(S25_PIENI)} ja ${FI.eur(60000)} palkalla ${FI.eur(S25_SUURI)}. Ero johtuu siitä, että suurempi tulo maksaa vähennetystä eurosta enemmän veroa.` },
      { q: 'Onko matkakulujen omavastuu 900 vai 800 euroa vuonna 2026?', a: `Voimassa oleva omavastuu on ${FI.eur(M.omavastuu)}. Hallitus on esittänyt sen laskemista ${FI.eur(ESITYS)} euroon samassa esityksessä, jossa ehdotetaan kotitalousvähennyksen korotusta, mutta muutos ei ole vielä voimassa. Jos se hyväksytään, ${KM} kilometrin työmatkalla verot pienenisivät noin ${FI.eur(ESITYS_LISA)} lisää. Enimmäismäärä ${FI.eur(M.enimmaismaara)} pysyisi ennallaan.` },
      { q: 'Saako omalla autolla ajetut kilometrit vähentää, vaikka bussi kulkisi?', a: `Pääsääntöisesti vähennys lasketaan halvimman kulkuneuvon mukaan. Jos julkinen liikenne on käytettävissä ja kohtuullinen, Verohallinto hyväksyy kuluiksi lipun hinnan, ei ${FI.eur(M.oma_auto_euroa_km, 2)} kilometrikustannusta. Oman auton kulut hyväksytään, kun julkista liikennettä ei ole tai sen käyttö ei ole työaikojen tai matkan takia mahdollista. Perustelut kannattaa kirjoittaa veroilmoitukseen.` },
      { q: 'Kannattaako matkakulut ilmoittaa verokorttiin vai veroilmoitukseen?', a: `Kumpikin tapa johtaa samaan lopulliseen veroon. Jos ilmoitat ${FI.eur(vahennys(K25))} vähennyksen jo verokorttia tilatessasi, ${FI.eur(PALKKA)} palkalla veroprosentti laskee ${FI.num(ILMAN.veroprosentti, 1)} prosentista ${FI.num(KANSSA.veroprosentti, 1)} prosenttiin ja hyöty tulee joka kuukausi. Jos ilmoitat kulut vasta esitäytetyssä veroilmoituksessa, sama summa palautuu veronpalautuksena verotuksen valmistuttua.` },
      { q: 'Mitä tapahtuu, jos matkakulut ylittävät 7000 euroa?', a: `Ylittävää osaa ei voi vähentää. Vähennyksen enimmäismäärä on ${FI.eur(M.enimmaismaara)} omavastuun jälkeen, joten omalla autolla katto täyttyy noin ${FI.num(KM_KATTO, 0)} kilometrin työmatkalla yhteen suuntaan, kun työpäiviä on ${PV}. Pidemmillä matkoilla jokainen lisäkilometri on verotuksessa ilmainen. Kaksi asuntoa tai viikkomatkat ovat eri tilanne, jota tämä laskelma ei kata.` },
    ],
    body: (h) => `
<h2>Vähennyksen kolme lukua</h2>
<p>Työmatkavähennys perustuu kolmeen lukuun, jotka Verohallinto on vahvistanut ${h.src('vero_ennakonpidatys', 'vuoden 2026 ennakonpidätyspäätöksessä')}. Omavastuu on ${h.eur(M.omavastuu)} vuodessa: sen alle jäävät kulut jäävät kokonaan itse maksettaviksi. Enimmäisvähennys on ${h.eur(M.enimmaismaara)} omavastuun jälkeen. Kun oman auton käyttö on perusteltua, kulut lasketaan ${h.eur(M.oma_auto_euroa_km, 2)} kilometriltä riippumatta auton todellisista kuluista, polttoaineesta tai siitä, onko auto sähköauto. Omavastuu on henkilökohtainen ja vähennetään kerran vuodessa, ei jokaisesta työsuhteesta erikseen.</p>
${h.table(['Matka yhteen suuntaan', 'Kulut vuodessa', 'Vähennys', 'Verot pienenevät'], MATKAT.map(({ km, k, v, s }) => [`${h.num(km)} km`, h.eur(k), h.eur(v), h.eur(s)]), `Oma auto, ${PV} työpäivää, palkka ${h.eur(PALKKA)}, Helsinki, vuosi 2026`, ['l', 'r', 'r', 'r'])}
<p>Taulukosta näkyy kaksi rajaa. Lyhyellä matkalla omavastuu syö koko kulun: ${h.num(KM_ALKAA, 1)} kilometriin asti vähennystä ei synny lainkaan. Pitkällä matkalla katto tulee vastaan noin ${h.num(KM_KATTO, 0)} kilometrin kohdalla, eikä sitä pidemmästä matkasta saa enää lisähyötyä. Näiden välissä jokainen lisäkilometri kasvattaa vähennystä tasaisesti. Taulukon säästösarake ei kasva yhtä tasaisesti, koska suuri vähennys voi pudottaa tulon alemmalle veroasteikon portaalle.</p>
<h2>Halvin kulkuneuvo ratkaisee</h2>
<p>Vähennys lasketaan halvimman käytettävissä olevan kulkuneuvon mukaan, vaikka todellisuudessa ajaisit omalla autolla. Jos bussi tai juna kulkee kotisi ja työpaikkasi välillä järkevästi, vähennyskelpoisia ovat lippujen hinnat. Kausilippu, joka maksaa esimerkiksi ${h.eur(60)} kuukaudessa yhdeltätoista kuukaudelta, tekee ${h.eur(LIPPU)} vuodessa, mikä jää alle omavastuun: vähennystä ei tule. Siksi monella kaupunkilaisella matkakuluvähennys jää kokonaan saamatta, vaikka työmatka olisi pitkä. Seutuliikenteessä tilanne on toinen: pitkän välimatkan kausiliput voivat ylittää omavastuun selvästi, ja silloin vähennykseen lasketaan omavastuun ylittävä osa lippujen todellisesta hinnasta.</p>
<p>Oman auton kulut hyväksytään, kun julkista liikennettä ei ole, se ei sovi työaikoihin tai matka pysäkille ja vaihtoineen veisi kohtuuttomasti aikaa. Yhdistelmämatkat ovat mahdollisia: jos ajat autolla asemalle ja jatkat junalla, vähennykseen lasketaan molempien osuuksien kulut. Työsuhdeautolla ajettujen matkojen kulut lasketaan eri perusteella kuin oman auton, eikä tämän sivun ${h.eur(M.oma_auto_euroa_km, 2)} kilometrihinta koske niitä.</p>
<h2>Miksi säästö on suurempi kuin kunnallisveroprosentti</h2>
<p>Matkakulut vähennetään puhtaasta ansiotulosta, eli ennen kuin kunnallisvero, valtionvero, sairaanhoitomaksu ja Yle-vero lasketaan. Siksi yksi vähennetty euro pienentää kaikkia niitä yhtä aikaa. ${h.eur(PALKKA)} palkalla ${h.eur(vahennys(K25))} vähennys pienentää veroja ${h.eur(S25)}, mikä on ${h.pct(S25 / vahennys(K25), 0)} vähennyksestä. Mukana on myös työtulovähennyksen vaikutus: ${h.eur(h.P.vero.tyotulovahennys.pienenemisraja)} ylittävällä tulolla työtulovähennys pienenee tulon kasvaessa, ja kun matkakulut pienentävät puhdasta ansiotuloa, työtulovähennystä jää enemmän jäljelle. Esimerkissämme työtulovähennys kasvaa ${h.eur(ILMAN.tyotulovahennys)} eurosta ${h.eur(KANSSA.tyotulovahennys)} euroon.</p>
<p>Pienituloisella sama vähennys on vähemmän arvokas. ${h.eur(25000)} palkalla ${KM} kilometrin työmatka säästää ${h.eur(S25_PIENI)}, koska työtulovähennys nollaa jo valmiiksi suuren osan veroista. ${h.eur(60000)} palkalla säästö on ${h.eur(S25_SUURI)}. Vähennyksen arvon omalla tulollasi näet ${h.a('verolaskuri', 'verolaskurilla')}, johon voi syöttää matkakulut suoraan.</p>
<h2>Esimerkki: hybridityö</h2>
<p>Etätyö on muuttanut monen työmatkavähennyksen. Jos käyt toimistolla kolmena päivänä viikossa, työmatkapäiviä kertyy noin ${h.num(PV_HYB)} vuodessa täyden ${h.num(PV)} päivän sijaan. ${KM} kilometrin matkalla oman auton kulut ovat silloin ${h.eur(K_HYB)}, vähennys omavastuun jälkeen ${h.eur(vahennys(K_HYB))} ja veron säästö ${h.eur(S_HYB)}, kun täysillä toimistopäivillä säästö olisi ${h.eur(S25)}. Omavastuu ei jousta työpäivien mukaan, joten pienikin pudotus päivissä leikkaa vähennystä suhteessa enemmän kuin kuluja. Jos matka on lyhyt ja toimistopäiviä on vähän, vähennys voi kadota kokonaan, vaikka työmatka olisi sama kuin ennen.</p>
<h2>Esitys omavastuun laskemisesta</h2>
<p>Hallitus on esittänyt, että matkakulujen omavastuu laskettaisiin ${h.eur(M.omavastuu)} eurosta ${h.eur(ESITYS)} euroon. Esitys julkaistiin ${h.src('vero_kotitalous_esitys', 'Verohallinnon tiedotteessa')} yhdessä ${h.a('kotitalousvahennys-laskuri', 'kotitalousvähennyksen')} korotusehdotuksen kanssa. Kun tätä sivua on päivitetty, muutosta ei ollut hyväksytty, joten laskelmat käyttävät voimassa olevaa omavastuuta. Jos esitys hyväksytään, jokainen omavastuun ylittävä työmatka hyötyisi ${h.eur(M.omavastuu - ESITYS)} suuremmasta vähennyksestä, mikä tarkoittaisi ${KM} kilometrin esimerkissämme noin ${h.eur(ESITYS_LISA)} pienempiä veroja. Enimmäismäärä pysyisi ennallaan.</p>
<h2>Miten vähennys haetaan</h2>
<p>Matkakulut voi ilmoittaa kahdessa vaiheessa. Verokorttia muuttaessa voit ilmoittaa arvion vuoden matkakuluista, jolloin ne pienentävät veroprosenttia heti: esimerkissämme prosentti laskee ${h.num(ILMAN.veroprosentti, 1)} prosentista ${h.num(KANSSA.veroprosentti, 1)} prosenttiin. Jos et tee mitään verokortille, kulut ilmoitetaan esitäytetyssä veroilmoituksessa, ja vähennyksen arvo palautuu ${h.a('veronpalautus', 'veronpalautuksena')}. Kummassakin tapauksessa kannattaa säilyttää laskelma työpäivistä ja matkan pituudesta, koska Verohallinto voi pyytää selvitystä. Oman auton käyttöä perustellessa hyödyllisiä tietoja ovat julkisen liikenteen aikataulut, lähimmän pysäkin etäisyys ja työvuorojen alkamis- ja päättymisajat. Jos perustelut eivät riitä, vähennys lasketaan lipun hinnasta, ja ero näkyy verotuspäätöksessä pienempänä vähennyksenä.</p>
<p>Työpäivien määrä on todellinen, ei teoreettinen. Lomat, sairauspoissaolot ja etätyöpäivät vähennetään, joten moni, joka tekee osan viikosta kotona, jää selvästi alle ${h.num(PV)} työmatkapäivän. Silloin myös kulut ja vähennys pienenevät, ja lyhyellä matkalla omavastuu voi jäädä kokonaan täyttymättä.</p>`,
  },
  en: {
    slug: 'commuting-deduction',
    nav: 'Commuting deduction',
    card: 'The 2026 commuting deduction: own share, cap, per-km rate by car and how much tax it saves.',
    title: `Commuting deduction 2026: ${EN.eur(M.omavastuu)} own share, ${EN.eur(M.oma_auto_euroa_km, 2)}/km by car`,
    description: `Finnish commuting deduction 2026: home-to-work costs above a ${EN.eur(M.omavastuu)} own share are deductible up to ${EN.eur(M.enimmaismaara)}, at ${EN.eur(M.oma_auto_euroa_km, 2)}/km by car when allowed. See your own saving.`,
    h1: 'The Finnish commuting deduction',
    intro: 'Travel between home and work is tax deductible in Finland once it costs more than a fixed own share each year.',
    resume: `In Finland you can deduct the cost of travel between home and work (matkakulut) above an own share (omavastuu) of ${EN.eur(M.omavastuu)} a year, up to a maximum deduction of ${EN.eur(M.enimmaismaara)}, in your 2026 taxes. Costs are counted for the cheapest means of transport available; where driving your own car is accepted, Vero uses ${EN.eur(M.oma_auto_euroa_km, 2)} per kilometre. A ${KM} km commute each way on ${PV} working days comes to ${EN.eur(K25)} a year by car, so ${EN.eur(vahennys(K25))} is deductible. On a ${EN.eur(PALKKA)} salary in Helsinki that cuts your taxes by ${EN.eur(S25)}. The saving is larger than your municipal tax rate suggests, because the deduction reduces net earned income and with it state tax, the health care contribution and Yle tax. If you take the bus in a city, a season ticket often stays under the own share and gives nothing. The government has proposed lowering the own share to ${EN.eur(ESITYS)}, but that is not law yet, so figures here use ${EN.eur(M.omavastuu)}.`,
    faqs: [
      { q: 'Can I deduct my commute in Finland if I take the bus?', a: `Yes, but only the ticket costs above the ${EN.eur(M.omavastuu)} own share. A season ticket of ${EN.eur(60)} a month for eleven months is ${EN.eur(LIPPU)} a year, below the threshold, so there is no deduction. Bus and train commuters only benefit when their annual fares exceed ${EN.eur(M.omavastuu)}, which mainly happens on long regional routes.` },
      { q: 'How far do I need to drive for the commuting deduction to help?', a: `At ${EN.eur(M.oma_auto_euroa_km, 2)} per km and ${PV} working days, your car costs pass the ${EN.eur(M.omavastuu)} own share at about ${EN.num(KM_ALKAA, 1)} km each way. The cap of ${EN.eur(M.enimmaismaara)} is reached at about ${EN.num(KM_KATTO, 0)} km. This assumes Vero accepts the car as your cheapest reasonable option, which it does when public transport is missing or impractical.` },
      { q: 'Is the commuting own share €900 or €800 in 2026?', a: `It is ${EN.eur(M.omavastuu)} under current law. A government proposal would lower it to ${EN.eur(ESITYS)} alongside a higher household tax credit, but it had not been adopted when this page was updated. If it passes, a ${KM} km commute would save about ${EN.eur(ESITYS_LISA)} more in tax. The ${EN.eur(M.enimmaismaara)} cap would stay the same.` },
      { q: 'Should I put commuting costs on my tax card or in my tax return?', a: `Either gives the same final tax. On your tax card the deduction lowers withholding straight away: at ${EN.eur(PALKKA)} with a ${KM} km drive the rate falls from ${EN.num(ILMAN.veroprosentti, 1)}% to ${EN.num(KANSSA.veroprosentti, 1)}%. If you wait and add the costs to your pre-filled tax return, the same amount comes back as a refund after the assessment.` },
      { q: 'What if my commuting costs are above the €7,000 cap?', a: `The excess is simply lost. The maximum deduction is ${EN.eur(M.enimmaismaara)} after the ${EN.eur(M.omavastuu)} own share, so a car commute stops adding anything at about ${EN.num(KM_KATTO, 0)} km each way on ${PV} days. Weekly travel to a second home is a different situation with its own rules, not covered by this calculation.` },
      { q: 'Do remote work days count for the commuting deduction?', a: `No. Only days you actually travel to the workplace count, so remote days, holidays and sick leave come off. Three office days a week give far fewer than ${PV} commuting days, which can push a short commute below the ${EN.eur(M.omavastuu)} own share. Keep a simple record of office days and distance in case Vero asks.` },
    ],
    body: (h) => `
<h2>Three numbers</h2>
<p>The deduction rests on three figures confirmed in ${h.src('vero_ennakonpidatys', 'Vero’s 2026 withholding decision')}. The own share is ${h.eur(M.omavastuu)} a year and stays at your own cost. The deduction is capped at ${h.eur(M.enimmaismaara)} after that. When using your own car is justified, costs are counted at ${h.eur(M.oma_auto_euroa_km, 2)} per kilometre, whatever your fuel bill and whether or not the car is electric. The own share is per person per year, not per job.</p>
${h.table(['One-way distance', 'Costs per year', 'Deduction', 'Tax saved'], MATKAT.map(({ km, k, v, s }) => [`${h.num(km)} km`, h.eur(k), h.eur(v), h.eur(s)]), `Own car, ${PV} working days, ${h.eur(PALKKA)} salary, Helsinki, 2026`, ['l', 'r', 'r', 'r'])}
<p>Up to about ${h.num(KM_ALKAA, 1)} km each way the own share swallows everything. Beyond about ${h.num(KM_KATTO, 0)} km the cap bites and extra distance brings nothing. In between, each kilometre adds to the deduction at the same rate.</p>
<h2>The cheapest means of transport</h2>
<p>Vero counts the cheapest means of transport you could reasonably use, not the one you choose. Where a bus or train serves your route at sensible times, your deduction is based on ticket prices even if you drive. That is why many city dwellers with long commutes never get anything: annual public transport costs rarely exceed ${h.eur(M.omavastuu)}. Your own car is accepted when there is no public transport, when it does not fit your working hours, or when getting to a stop and changing would take unreasonable time. Combined trips count too, for example driving to a station and taking the train. Trips in a company car use a different basis and the ${h.eur(M.oma_auto_euroa_km, 2)} rate does not apply.</p>
<h2>Why the saving beats your municipal tax rate</h2>
<p>Commuting costs come off net earned income, before municipal tax, state tax, the health care contribution and Yle tax are calculated, so every deducted euro reduces all of them. On ${h.eur(PALKKA)}, a ${h.eur(vahennys(K25))} deduction saves ${h.eur(S25)}, which is ${h.pct(S25 / vahennys(K25), 0)} of the deduction. Part of that comes from the earned income credit: above ${h.eur(h.P.vero.tyotulovahennys.pienenemisraja)} the credit shrinks as income rises, so lowering net income gives some of it back. In our example the credit rises from ${h.eur(ILMAN.tyotulovahennys)} to ${h.eur(KANSSA.tyotulovahennys)}. On ${h.eur(25000)} the same commute saves only ${h.eur(S25_PIENI)}; on ${h.eur(60000)} it saves ${h.eur(S25_SUURI)}. Try your own figures in the ${h.a('verolaskuri', 'tax calculator')}.</p>
<h2>Hybrid work</h2>
<p>Remote work has quietly shrunk many commuting deductions. Three office days a week means roughly ${h.num(PV_HYB)} commuting days a year instead of ${h.num(PV)}. On the same ${KM} km drive, costs fall to ${h.eur(K_HYB)}, the deduction to ${h.eur(vahennys(K_HYB))} and the tax saving to ${h.eur(S_HYB)}, against ${h.eur(S25)} with a full office week. The own share does not scale with your days, so a drop in office days cuts the deduction proportionally more than it cuts your costs. On a short commute it can disappear altogether.</p>
<h2>The proposed lower own share</h2>
<p>The government has proposed cutting the own share from ${h.eur(M.omavastuu)} to ${h.eur(ESITYS)}, announced in ${h.src('vero_kotitalous_esitys', 'a Vero press release')} together with a higher ${h.a('kotitalousvahennys-laskuri', 'household tax credit')}. It was not law when this page was last updated, so all figures here use ${h.eur(M.omavastuu)}. If adopted, every commute above the threshold would gain ${h.eur(M.omavastuu - ESITYS)} of extra deduction, about ${h.eur(ESITYS_LISA)} of tax in our ${KM} km example.</p>
<h2>How to claim it</h2>
<p>You can claim on your tax card, by entering estimated annual commuting costs when you revise it in MyTax (OmaVero), or afterwards in the pre-filled tax return, in which case the value comes back as a ${h.a('veronpalautus', 'tax refund')}. Count real commuting days only. Keep a note of distance and office days, because Vero may ask you to explain why the car rather than public transport was necessary.</p>`,
  },
});
