import { definePage } from '../../lib/guide-types';
import { P, FI, EN } from '../../lib/fmt';
import { laskeVerot } from '../../lib/engine/vero';

const V = P.vero;
const SHM = V.sairaanhoitomaksu_palkka_prosentti, SHM_MUU = V.sairaanhoitomaksu_muu_tulo_prosentti, KOR = V.sairaanhoitomaksu_korotus_prosentti;
const PVM = V.paivarahamaksu_prosentti, RAJA = V.paivarahamaksu_tuloraja;
const VMV = P.vanhempainraha.vakuutusmaksuvahennys_prosentti;

const A = laskeVerot({ tulo: 36000 });
const ALLE = laskeVerot({ tulo: RAJA - 1 });
const YLI = laskeVerot({ tulo: RAJA });
const PIENI = laskeVerot({ tulo: 25000 });
const SUURI = laskeVerot({ tulo: 80000 });
const EL = laskeVerot({ tulo: 24000, tulolaji: 'elake' });
const ET = laskeVerot({ tulo: 24000, tulolaji: 'etuus' });
const PA = laskeVerot({ tulo: 24000 });
const KAKSI_A = 9000, KAKSI_B = 9000;
const KAKSI = laskeVerot({ tulo: KAKSI_A + KAKSI_B });
const NIMELLINEN = PIENI.verotettava * SHM / 100;
const TASOT = [15000, RAJA, 25000, 36000, 50000, 80000].map((t) => ({ t, v: laskeVerot({ tulo: t }) }));

export default definePage({
  id: 'sairausvakuutusmaksut',
  group: 'vero',
  order: 90,
  mini: 'svmaksut',
  related: ['tyoelakemaksu', 'yle-vero', 'veroprosenttilaskuri', 'vanhempainpaivaraha-laskuri'],
  sources: ['vero_veroperusteet', 'vero_ennakonpidatys'],
  fi: {
    slug: 'sairausvakuutusmaksu',
    nav: 'Sairausvakuutusmaksut',
    card: 'Sairaanhoitomaksu ja päivärahamaksu 2026: prosentit, tuloraja ja mihin maksut menevät.',
    title: 'Sairausvakuutusmaksu 2026: sairaanhoito- ja päivärahamaksu',
    description: `Sairausvakuutusmaksut 2026: sairaanhoitomaksu ${FI.p(SHM)} palkkatulosta ja ${FI.p(SHM_MUU)} eläkkeestä, päivärahamaksu ${FI.p(PVM)} kun vuoden palkka on vähintään ${FI.eur(RAJA)}.`,
    h1: 'Sairausvakuutusmaksut: sairaanhoitomaksu ja päivärahamaksu',
    intro: 'Palkansaaja maksaa sairausvakuutukseen kahta maksua, jotka lasketaan eri pohjasta ja joilla on eri tuloraja.',
    resume: `Palkansaajan sairausvakuutusmaksut ovat vuonna 2026 sairaanhoitomaksu ${FI.p(SHM)} ja päivärahamaksu ${FI.p(PVM)}. Sairaanhoitomaksu lasketaan kunnallisverotuksessa verotettavasta tulosta, päivärahamaksu suoraan bruttopalkasta. ${FI.eur(36000)} vuodessa ansaitseva maksaa sairaanhoitomaksua ${FI.eur(A.sairaanhoitomaksu)} ja päivärahamaksua ${FI.eur(A.paivarahamaksu)}, yhteensä ${FI.eur(A.sairaanhoitomaksu + A.paivarahamaksu)} vuodessa. Päivärahamaksua ei peritä lainkaan, jos vuoden palkkatulot jäävät alle ${FI.eur(RAJA)}; rajan ylittyessä maksu lasketaan koko palkasta, ei vain ylittävästä osasta. Eläkkeestä ja Kelan etuuksista sairaanhoitomaksu on korkeampi, ${FI.p(SHM_MUU)}, koska siihen lisätään ${FI.p(KOR)} korotus, mutta päivärahamaksua niistä ei makseta. Molemmat maksut sisältyvät verokortin veroprosenttiin. Päivärahamaksu on vähennyskelpoinen ja pienentää verotettavaa tuloa, sairaanhoitomaksu ei. Pienituloisella työtulovähennys voi nollata sairaanhoitomaksun kokonaan, kun taas päivärahamaksuun se ei vaikuta. Kuukausitasolla ${FI.eur(3000)} palkasta maksuihin menee noin ${FI.eur((A.sairaanhoitomaksu + A.paivarahamaksu) / 12)}, eikä summa näy palkkalaskelmalla omana rivinään, koska se on osa verokortin prosenttia.`,
    faqs: [
      { q: 'Miksi päivärahamaksu alkaa yhtäkkiä, kun palkka ylittää rajan?', a: `Päivärahamaksu ei porrastu, vaan se peritään koko palkasta heti, kun vuoden palkkatulot ovat vähintään ${FI.eur(RAJA)}. Euroa pienemmällä palkalla maksua ei ole, rajalla se on ${FI.eur(YLI.paivarahamaksu, 2)}. Laskelmamme mukaan nettotulo on rajalla ${FI.eur(ALLE.netto - YLI.netto)} pienempi kuin euroa aiemmin. Raja koskee koko vuoden palkkaa yhteensä kaikista työsuhteista, ei yksittäistä kuukautta tai yhtä työnantajaa.` },
      { q: 'Paljonko sairaanhoitomaksua menee eläkkeestä?', a: `Eläkkeestä sairaanhoitomaksu on ${FI.p(SHM_MUU)} verotettavasta tulosta, eli ${FI.p(KOR)} enemmän kuin palkasta. ${FI.eur(24000)} vuodessa eläkettä saava maksaa sitä ${FI.eur(EL.sairaanhoitomaksu, 2)}. Päivärahamaksua eläkkeestä ei peritä. Jos eläkeläinen tekee lisäksi palkkatyötä, palkasta sairaanhoitomaksu lasketaan palkkatulon prosentilla, ja jos palkat ylittävät rajan, myös päivärahamaksu peritään.` },
      { q: 'Onko päivärahamaksu vähennyskelpoinen verotuksessa?', a: `On. Päivärahamaksu vähennetään puhtaasta ansiotulosta samaan tapaan kuin työeläkemaksu ja työttömyysvakuutusmaksu, ennen perusvähennystä. ${FI.eur(36000)} palkalla vähennys on ${FI.eur(A.paivarahamaksu)}, ja se pienentää sekä kunnallisveroa että sairaanhoitomaksua. Sairaanhoitomaksu itse ei ole vähennyskelpoinen, koska se on veroluonteinen maksu, joka lasketaan jo vähennysten jälkeisestä tulosta.` },
      { q: 'Mitä päivärahamaksulla rahoitetaan?', a: `Päivärahamaksu rahoittaa sairausvakuutuksen ansiosidonnaisia päivärahoja, kuten sairauspäivärahaa ja vanhempainpäivärahoja. Kun Kela laskee päivärahan, se vähentää vuosituloista vakuutusmaksuvähennyksen ${FI.p(VMV)}, joka vastaa palkansaajan maksuja. Sairaanhoitomaksulla katetaan sairaanhoidon korvauksia, kuten lääkkeiden ja matkojen korvauksia. Maksun maksaminen ei ole päivärahan ehto, mutta päivärahan suuruus riippuu aiemmista työtuloista.` },
      { q: 'Paljonko sairausvakuutusmaksut ovat kuukaudessa 3000 euron palkasta?', a: `${FI.eur(3000)} kuukausipalkasta eli ${FI.eur(36000)} vuodessa sairaanhoitomaksua kertyy ${FI.eur(A.sairaanhoitomaksu)} ja päivärahamaksua ${FI.eur(A.paivarahamaksu)} vuodessa. Kuukautta kohden se tekee noin ${FI.eur(A.sairaanhoitomaksu / 12)} ja ${FI.eur(A.paivarahamaksu / 12)}. Luvut on laskettu Helsingin kunnallisverolla ilman kirkon jäsenyyttä; kotikunta ei vaikuta maksuihin, mutta lomaraha ja muut lisät kasvattavat molempien pohjaa.` },
      { q: 'Lasketaanko päivärahamaksun raja jokaisesta työpaikasta erikseen?', a: `Ei lasketa. Raja ${FI.eur(RAJA)} koskee kaikkia vuoden palkkatuloja yhteensä. Jos ansaitset kahdessa osa-aikatyössä ${FI.eur(KAKSI_A)} ja ${FI.eur(KAKSI_B)}, kumpikaan ei yksin ylitä rajaa, mutta yhteensä ylität sen, ja päivärahamaksu on ${FI.eur(KAKSI.paivarahamaksu)}. Jos verokorttisi tuloraja on arvioitu oikein, maksu sisältyy jo pidätykseen; muuten se peritään verotuksessa.` },
      { q: 'Maksetaanko sairaanhoitomaksua työttömyysetuudesta?', a: `Maksetaan, ja korotetulla ${FI.p(SHM_MUU)} prosentilla, koska etuus ei ole palkkatuloa. ${FI.eur(24000)} vuodessa etuutta saava maksaa sairaanhoitomaksua ${FI.eur(ET.sairaanhoitomaksu, 2)}, kun saman summan palkasta se olisi vain ${FI.eur(PA.sairaanhoitomaksu, 2)}. Ero kasvaa, koska etuudesta ei saa työtulovähennystä, joka palkansaajalla syö osan sairaanhoitomaksusta.` },
    ],
    body: (h) => `
<h2>Kaksi maksua, kaksi pohjaa</h2>
<p>Sairausvakuutusmaksut sekoitetaan usein yhdeksi maksuksi, mutta Verohallinnon ${h.src('vero_ennakonpidatys', 'ennakonpidätyspäätöksessä')} ne lasketaan erikseen ja eri summista. Sairaanhoitomaksu on ${h.num(SHM, 2)} % samasta verotettavasta tulosta, josta lasketaan kunnallisvero, eli tulosta, josta on jo vähennetty maksut ja perusvähennys. Päivärahamaksu taas on ${h.num(PVM, 2)} % bruttopalkasta ilman mitään vähennyksiä. Tästä seuraa, että sairaanhoitomaksu reagoi vähennyksiin ja työtulovähennykseen, päivärahamaksu ei.</p>
${h.table(['Vuosipalkka', 'Sairaanhoitomaksu', 'Päivärahamaksu', 'Yhteensä', 'Osuus palkasta'], TASOT.map(({ t, v }) => [h.eur(t), h.eur(v.sairaanhoitomaksu), h.eur(v.paivarahamaksu), h.eur(v.sairaanhoitomaksu + v.paivarahamaksu), h.pct((v.sairaanhoitomaksu + v.paivarahamaksu) / t, 2)]), 'Palkansaaja, Helsinki, vuosi 2026', ['l', 'r', 'r', 'r', 'r'])}
<p>Pienimmällä palkalla kumpaakaan maksua ei käytännössä ole. Päivärahamaksu puuttuu, koska palkka jää alle rajan, ja sairaanhoitomaksun syö työtulovähennys, joka ylittää valtionveron ja kohdistuu siksi myös kunnallisveroon ja sairaanhoitomaksuun. ${h.eur(25000)} palkalla sairaanhoitomaksua jää jäljelle vain ${h.eur(PIENI.sairaanhoitomaksu, 2)}, vaikka päivärahamaksu on jo täysimääräinen ${h.eur(PIENI.paivarahamaksu)}. ${h.eur(80000)} palkalla sairaanhoitomaksu on ${h.eur(SUURI.sairaanhoitomaksu)} ja päivärahamaksu ${h.eur(SUURI.paivarahamaksu)}.</p>
<h2>Miten työtulovähennys pienentää sairaanhoitomaksua</h2>
<p>Työtulovähennys vähennetään ensin valtionverosta. Jos valtionveroa on vähemmän kuin vähennystä, ylijäämä jaetaan kunnallisveron, kirkollisveron ja sairaanhoitomaksun kesken niiden euromäärien suhteessa. ${h.eur(25000)} palkalla verotettava tulo on ${h.eur(PIENI.verotettava)}, joten sairaanhoitomaksu olisi ilman työtulovähennystä ${h.eur(NIMELLINEN, 2)}. Koska valtionveroa ei tällä tulotasolla synny lainkaan, työtulovähennys ${h.eur(PIENI.tyotulovahennys)} kohdistuu kokonaan muihin veroihin, ja sairaanhoitomaksusta jää maksettavaksi ${h.eur(PIENI.sairaanhoitomaksu, 2)}. Päivärahamaksuun työtulovähennys ei koskaan kohdistu, joten se on pienituloiselle usein suurempi kuin sairaanhoitomaksu.</p>
<h2>Päivärahamaksun tuloraja on porras</h2>
<p>Päivärahamaksua ei peritä, jos vuoden palkkatulot jäävät alle ${h.eur(RAJA)}. Raja ei ole verovapaa osuus vaan kynnys: kun se ylittyy, ${h.num(PVM, 2)} % lasketaan koko palkasta. ${h.eur(RAJA - 1)} palkalla päivärahamaksua ei ole, ${h.eur(RAJA)} palkalla se on ${h.eur(YLI.paivarahamaksu, 2)}. Koska maksu on vähennyskelpoinen ja lisäksi Yle-vero kasvaa, nettotulo laskee rajalla ${h.eur(ALLE.netto - YLI.netto, 2)}. Osa-aikatyötä tekevän kannattaa tietää porras, mutta se ei ole syy kieltäytyä lisätunneista: muutaman sadan euron lisäpalkka kattaa eron.</p>
<p>Raja lasketaan vuoden palkkatuloista, eikä työnantaja voi tietää muiden työsuhteiden palkkoja. Siksi Verohallinto ottaa päivärahamaksun huomioon verokortin prosentissa arvioidun vuositulon perusteella, ja lopullinen maksu ratkeaa verotuksessa. Jos arvioit tulosi rajan alle mutta ylität sen, maksu peritään jäännösverona.</p>
<h2>Kaksi osa-aikatyötä</h2>
<p>Päivärahamaksun raja koskee kaikkia palkkoja yhteensä. Kaksi ${h.eur(KAKSI_A)} vuodessa maksavaa osa-aikatyötä jää kumpikin yksinään selvästi alle rajan, mutta yhdessä ne tekevät ${h.eur(KAKSI_A + KAKSI_B)}, ja päivärahamaksu on ${h.eur(KAKSI.paivarahamaksu)}. Molemmat työnantajat pidättävät veron saman verokortin perusteella, joten oikein arvioitu tuloraja ratkaisee, tuleeko maksu pidätetyksi jo vuoden aikana. Tässä tilanteessa sairaanhoitomaksua ei käytännössä synny lainkaan, koska työtulovähennys kattaa sen: koko vuoden sairaanhoitomaksu on ${h.eur(KAKSI.sairaanhoitomaksu)}.</p>
<h2>Eläke ja etuudet: korotettu sairaanhoitomaksu</h2>
<p>Muusta kuin palkka- ja yrittäjätulosta sairaanhoitomaksu on ${h.num(SHM_MUU, 2)} %. Se koostuu perusmaksusta ${h.num(SHM, 2)} % ja korotuksesta ${h.num(KOR, 2)} %, jotka ${h.src('vero_veroperusteet', 'vero.fi:n veroperusteissa')} esitetään yhdessä. Korotus koskee eläkettä, työttömyysetuutta, vanhempainrahaa ja muita etuuksia. ${h.eur(24000)} vuodessa saava maksaa sairaanhoitomaksua eläkkeestä ${h.eur(EL.sairaanhoitomaksu, 2)}, etuudesta ${h.eur(ET.sairaanhoitomaksu, 2)} ja palkasta ${h.eur(PA.sairaanhoitomaksu, 2)}. Eläkkeen pienempi summa johtuu eläketulovähennyksestä, joka pienentää verotettavaa tuloa.</p>
<p>Päivärahamaksua näistä tuloista ei peritä, koska se kuuluu vain työtuloihin. Eläkeläisen, joka käy töissä, palkasta päivärahamaksu peritään normaalisti, jos palkkatulot ylittävät rajan.</p>
<h2>Mihin maksut kohdistuvat</h2>
<p>Sairausvakuutus jakautuu kahteen osaan. Sairaanhoitomaksulla rahoitetaan sairaanhoitovakuutusta, josta maksetaan esimerkiksi lääkekorvauksia ja matkakorvauksia. Päivärahamaksu rahoittaa työtulovakuutusta, josta maksetaan ansiotuloihin perustuvia päivärahoja: sairauspäivärahaa, vanhempainpäivärahoja ja kuntoutusrahaa. Työnantaja maksaa lisäksi omaa sairausvakuutusmaksuaan, joka ei näy palkkalaskelmalla. Palkansaajan osuudet ovat siis vain osa vakuutuksen rahoituksesta, ja niiden suuruus vahvistetaan vuosittain, minkä vuoksi prosentit kannattaa tarkistaa jokaisen verovuoden alussa.</p>
<p>Yhteys näkyy, kun Kela laskee päivärahan. Kela ei käytä bruttotuloa sellaisenaan, vaan vähentää siitä vakuutusmaksuvähennyksen ${h.num(VMV, 2)} %. Siksi ${h.a('vanhempainpaivaraha-laskuri', 'vanhempainpäivärahan laskuri')} lähtee vähennetystä vuositulosta eikä palkkalaskelman bruttosummasta.</p>
<h2>Palkkalaskelmalla</h2>
<p>Sairausvakuutusmaksut eivät näy palkkalaskelmalla omina riveinään, koska ne sisältyvät verokortin veroprosenttiin yhdessä valtionveron, kunnallisveron ja ${h.a('yle-vero', 'Yle-veron')} kanssa. Erikseen näkyvät vain ${h.a('tyoelakemaksu', 'työeläkemaksu')} ja työttömyysvakuutusmaksu. ${h.a('veroprosenttilaskuri', 'Veroprosenttilaskuri')} erittelee sairaanhoitomaksun ja päivärahamaksun omille riveilleen, joten näet, kuinka suuri osa verokortin prosentista on maksuja.</p>
<p>Lomaraha, ylityökorvaukset, bonukset ja verotettavat luontoisedut ovat palkkaa myös sairausvakuutusmaksujen kannalta. Ne kasvattavat päivärahamaksun pohjaa euro eurolta ja voivat nostaa vuoden palkkatulot rajan yli, vaikka kuukausipalkka yksinään jäisi sen alle. Kun arvioit vuositulojasi verokorttia varten, ota nämä erät mukaan, niin päivärahamaksu tulee pidätetyksi tasaisesti eikä jäännösverona seuraavana vuonna.</p>`,
  },
  en: {
    slug: 'health-insurance-contributions',
    nav: 'Health insurance contributions',
    card: 'The health care and daily allowance contributions for 2026: rates, threshold and what they pay for.',
    title: 'Health insurance contributions 2026: what Finland deducts',
    description: `Health insurance contributions 2026 in Finland: ${EN.p(SHM)} health care contribution on wages, ${EN.p(SHM_MUU)} on pensions, and a ${EN.p(PVM)} daily allowance fee from ${EN.eur(RAJA)}.`,
    h1: 'Finnish health insurance contributions',
    intro: 'Two small contributions fund Finland’s health insurance, and they are worked out on different amounts with different rules.',
    resume: `Employees in Finland pay two health insurance contributions in 2026: the health care contribution (sairaanhoitomaksu) of ${EN.p(SHM)} and the daily allowance contribution (päivärahamaksu) of ${EN.p(PVM)}. The first is charged on municipal taxable income, the second on gross pay. On ${EN.eur(36000)} a year that is ${EN.eur(A.sairaanhoitomaksu)} plus ${EN.eur(A.paivarahamaksu)}, ${EN.eur(A.sairaanhoitomaksu + A.paivarahamaksu)} in total. The daily allowance contribution only applies once annual wages reach ${EN.eur(RAJA)}, and then on the whole amount, not just the part above it. Pensions and Kela benefits carry a higher health care contribution of ${EN.p(SHM_MUU)}, which includes a ${EN.p(KOR)} surcharge, but no daily allowance contribution. Neither appears on your payslip as a separate line: both are built into the withholding rate on your tax card (verokortti). The daily allowance contribution is deductible from your income; the health care contribution is not. On low pay the earned income tax credit can wipe the health care contribution out entirely.`,
    faqs: [
      { q: 'Why can I not find the health insurance contribution on my Finnish payslip?', a: `Because it is inside your tax percentage. Vero builds both the ${EN.p(SHM)} health care contribution and the ${EN.p(PVM)} daily allowance contribution into the withholding rate, together with state, municipal and Yle tax. The only contributions shown separately are the ${EN.p(V.tyoelakemaksu_prosentti)} pension contribution and the ${EN.p(V.tyottomyysvakuutusmaksu_prosentti)} unemployment insurance contribution.` },
      { q: 'What is the päivärahamaksu threshold in 2026?', a: `${EN.eur(RAJA)} of wages for the year. Below it no daily allowance contribution is charged; at or above it, ${EN.p(PVM)} applies to every euro of pay. On exactly ${EN.eur(RAJA)} the contribution is ${EN.eur(YLI.paivarahamaksu, 2)}, and our calculation shows annual take-home ${EN.eur(ALLE.netto - YLI.netto)} lower than one euro below the line. The threshold covers all your jobs together, so it is settled in the final assessment.` },
      { q: 'Why is the health care contribution higher on my pension?', a: `On income other than wages, such as pensions or Kela benefits, the rate is ${EN.p(SHM_MUU)}: the base ${EN.p(SHM)} plus a ${EN.p(KOR)} surcharge. A ${EN.eur(24000)} pension pays ${EN.eur(EL.sairaanhoitomaksu, 2)}, while the same amount in benefits pays ${EN.eur(ET.sairaanhoitomaksu, 2)}; the pension figure is lower because the pension income deduction shrinks the base. No daily allowance contribution is charged on either.` },
      { q: 'Can I deduct the daily allowance contribution in my Finnish tax return?', a: `You do not need to claim it: Vero deducts it automatically. The daily allowance contribution comes off your net earned income before the basic deduction, just like the pension and unemployment contributions. On ${EN.eur(36000)} it is ${EN.eur(A.paivarahamaksu)}, which lowers municipal tax and the health care contribution. The health care contribution itself is not deductible.` },
      { q: 'Is the health care contribution charged on unemployment benefit?', a: `Yes, at the higher ${EN.p(SHM_MUU)} rate, because benefits are not wages. On ${EN.eur(24000)} of unemployment benefit it comes to ${EN.eur(ET.sairaanhoitomaksu, 2)}, against ${EN.eur(PA.sairaanhoitomaksu, 2)} on the same amount of salary. The gap also reflects the earned income credit, which wage earners get and benefit recipients do not.` },
      { q: 'Do these contributions give me the right to Kela sickness or parental allowance?', a: `Your allowance depends on your earnings and residence in the Finnish social security system, not on having paid a contribution as such. The link shows in the arithmetic: when Kela works out an earnings-related daily allowance, it first takes ${EN.p(VMV)} off your annual income as an insurance contribution deduction. That is why the ${EN.p(PVM)} contribution funds sickness, parental and rehabilitation allowances.` },
    ],
    body: (h) => `
<h2>Two contributions, two bases</h2>
<p>Under ${h.src('vero_ennakonpidatys', 'Vero’s 2026 withholding rules')} the two health insurance contributions are calculated separately. The health care contribution is ${h.num(SHM, 2)}% of the same taxable income used for municipal tax, after work expenses, employee contributions and the basic deduction. The daily allowance contribution is ${h.num(PVM, 2)}% of gross wages with nothing deducted. As a result, deductions and the earned income tax credit lower the first but never the second.</p>
${h.table(['Annual salary', 'Health care contribution', 'Daily allowance contribution', 'Total', 'Share of pay'], TASOT.map(({ t, v }) => [h.eur(t), h.eur(v.sairaanhoitomaksu), h.eur(v.paivarahamaksu), h.eur(v.sairaanhoitomaksu + v.paivarahamaksu), h.pct((v.sairaanhoitomaksu + v.paivarahamaksu) / t, 2)]), 'Employee in Helsinki, 2026', ['l', 'r', 'r', 'r', 'r'])}
<p>At the bottom of the table neither contribution really bites: wages are under the threshold, and the earned income credit (työtulovähennys) exceeds state tax and spills over onto municipal tax and the health care contribution. At ${h.eur(25000)} only ${h.eur(PIENI.sairaanhoitomaksu, 2)} of health care contribution is left, while the daily allowance contribution is already a full ${h.eur(PIENI.paivarahamaksu)}.</p>
<h2>The threshold is a cliff, not an allowance</h2>
<p>The ${h.eur(RAJA)} limit works as a switch. One euro below it, you pay no daily allowance contribution; at the limit, ${h.num(PVM, 2)}% is charged on your entire pay, ${h.eur(YLI.paivarahamaksu, 2)}. Even after the contribution reduces your taxable income, take-home pay drops by ${h.eur(ALLE.netto - YLI.netto, 2)} at that point. For a part-time worker it is worth knowing, but rarely a reason to turn down hours: a few hundred euros more pay covers the step.</p>
<p>Your employer cannot see what you earn elsewhere, so Vero builds the contribution into your tax card rate from the annual income you estimated. If you said you would stay under the threshold and then crossed it, the contribution is collected as residual tax after the assessment.</p>
<h2>How the earned income credit eats the health care contribution</h2>
<p>The earned income credit is taken off state tax first. When state tax is smaller than the credit, the remainder is shared between municipal tax, church tax and the health care contribution in proportion to their size. At ${h.eur(25000)} taxable income is ${h.eur(PIENI.verotettava)}, so the nominal health care contribution would be ${h.eur(NIMELLINEN, 2)}. There is no state tax at that level, so the whole ${h.eur(PIENI.tyotulovahennys)} credit lands on the other items and only ${h.eur(PIENI.sairaanhoitomaksu, 2)} remains. The credit never touches the daily allowance contribution, which is why it is often the larger of the two on modest pay.</p>
<h2>Two part-time jobs</h2>
<p>The threshold covers all your wages for the year. Two part-time jobs paying ${h.eur(KAKSI_A)} each are both well below it on their own, yet together they reach ${h.eur(KAKSI_A + KAKSI_B)} and trigger a daily allowance contribution of ${h.eur(KAKSI.paivarahamaksu)}. Both employers withhold from the same tax card, so the income limit you gave Vero decides whether the contribution is collected during the year or afterwards.</p>
<h2>Pensions and benefits</h2>
<p>For pensions, unemployment benefit, parental allowance and other benefits, the health care contribution is ${h.num(SHM_MUU, 2)}%: the base ${h.num(SHM, 2)}% plus a ${h.num(KOR, 2)}% surcharge, both listed on ${h.src('vero_veroperusteet', 'vero.fi’s 2026 tax bases')}. Benefits also get no earned income credit, so on ${h.eur(24000)} the health care contribution is ${h.eur(ET.sairaanhoitomaksu, 2)} from benefits against ${h.eur(PA.sairaanhoitomaksu, 2)} from wages. No daily allowance contribution is charged on pensions or benefits, since it belongs to work income only.</p>
<h2>What the money pays for</h2>
<p>Finnish health insurance has two parts. The health care contribution funds medical care insurance, which covers reimbursements such as medicine and travel costs. The daily allowance contribution funds earned-income insurance, which pays sickness allowance, parental allowances and rehabilitation allowance based on your previous earnings. Your employer pays its own health insurance contribution on top, which never appears on your payslip.</p>
<p>When Kela calculates a daily allowance, it reduces your annual income by an insurance contribution deduction of ${h.num(VMV, 2)}% before applying its formula. The ${h.a('vanhempainpaivaraha-laskuri', 'parental allowance calculator')} does the same, so its result starts from a slightly lower figure than your gross salary.</p>
<h2>On your payslip</h2>
<p>Look for the ${h.a('tyoelakemaksu', 'pension contribution')} and unemployment insurance as separate deductions; the health insurance contributions sit inside the tax line, together with the ${h.a('yle-vero', 'Yle tax')}. The ${h.a('veroprosenttilaskuri', 'tax rate calculator')} splits them out so you can see how much of your percentage is contributions rather than tax.</p>`,
  },
});
