/** Etusivu (pilarisivu) molemmilla kielillä. Kaikki lakiin perustuvat luvut h.P:stä tai moottorista, ei käsin. */
import type { FAQ, Helpers } from '../lib/guide-types';
import { HALVIN, KALLEIN, MEDIAANI, KUNTIA, AHVENANMAAN_KUNTIA, netto, VERO_ESIMERKKEJA } from '../lib/esimerkit';
import { kunta } from '../lib/engine/params';

const HKI = netto(3500, 'Helsinki'), POM = netto(3500, KALLEIN.nimi), TRE = netto(3500, 'Tampere'), MH = netto(3500, 'Maarianhamina');
const ERO = (POM.netto - HKI.netto) / 12;
const hkiK = kunta('Helsinki'), treK = kunta('Tampere'), mhK = kunta('Maarianhamina');

interface HomeText { title: string; description: string; h1: string; intro: string; resume: (h: Helpers) => string; faqs: (h: Helpers) => FAQ[]; body: (h: Helpers) => string }

export const HOME: Record<'fi' | 'en', HomeText> = {
  fi: {
    title: 'Nettopalkka 2026: palkkalaskuri jokaisen kunnan verolla',
    description: 'Nettopalkka 2026 kotikuntasi todellisella veroprosentilla: valtion asteikko, kunnallisvero kaikista 308 kunnasta, kirkollisvero, TyEL ja Yle-vero eriteltyinä.',
    h1: 'Nettopalkka 2026 kunnittain',
    intro: 'Bruttopalkasta käteen jäävä summa vuoden 2026 veroperusteilla ja juuri sinun kotikuntasi kunnallisveroprosentilla.',
    resume: (h) => `Kun bruttopalkka on ${h.eur(3500)} kuukaudessa, Helsingissä asuvalle jää vuonna 2026 käteen keskimäärin ${h.eur(HKI.netto / 12)} kuukaudessa, mutta ${KALLEIN.nimi}lla sama palkka antaa vain ${h.eur(POM.netto / 12)}. Ero, ${h.eur(-ERO)} kuussa, johtuu yksinomaan kunnallisverosta: Helsingissä se on ${h.num(hkiK.kunta, 2)} %, ${KALLEIN.nimi}lla ${h.num(KALLEIN.kunta, 2)} %, ja kaikkien ${KUNTIA} kunnan mediaani on ${h.num(MEDIAANI, 2)} %. Muut palkasta tehtävät pidätykset ovat kaikille samat: valtion progressiivinen tulovero, josta työtulovähennys (enintään ${h.eur(h.P.vero.tyotulovahennys.enimmaismaara)}) vähennetään ensin, sairaanhoitomaksu ${h.num(h.P.vero.sairaanhoitomaksu_palkka_prosentti, 2)} %, päivärahamaksu ${h.num(h.P.vero.paivarahamaksu_prosentti, 2)} % ja Yle-vero enintään ${h.eur(h.P.vero.yle.enimmaismaara)}, sekä työntekijän työeläkemaksu ${h.num(h.P.vero.tyoelakemaksu_prosentti, 2)} % ja työttömyysvakuutusmaksu ${h.num(h.P.vero.tyottomyysvakuutusmaksu_prosentti, 2)} %. Kirkon jäsenelle tulee lisäksi seurakunnan vero. Laskuri käyttää Verohallinnon 18.11.2025 vahvistamia kuntien ja seurakuntien prosentteja sekä vuoden 2026 valtion veroasteikkoa, ja se toistaa Verohallinnon julkaisemat ${VERO_ESIMERKKEJA} esimerkkiveroa palkasta, etuudesta ja eläkkeestä sentin tarkkuudella.`,
    faqs: (h) => [
      { q: 'Paljonko 3 500 euron kuukausipalkasta jää käteen vuonna 2026?', a: `Helsingissä ilman kirkollisveroa noin ${h.eur(HKI.netto / 12)} kuukaudessa, Tampereella ${h.eur(TRE.netto / 12)} ja ${KALLEIN.nimi}lla ${h.eur(POM.netto / 12)}. Luku on vuoden todellinen nettotulo jaettuna kahdellatoista. Verokortin pyöristys puolen prosenttiyksikön tarkkuudella ylöspäin voi pienentää kuukausierää hieman, mutta erotus palautuu veronpalautuksena seuraavana vuonna.` },
      { q: 'Miksi Ahvenanmaalla nettopalkka on suurempi, vaikka kunnallisvero on korkea?', a: `Ahvenanmaan kunnissa kunnallisvero on ${h.num(mhK.kunta, 2)}–19,70 %, mutta valtion tuloveron prosentteja alennetaan siellä ${h.num(h.P.vero.ahvenanmaa_asteikon_alennus_prosenttiyksikkoa, 2)} prosenttiyksiköllä, koska maakunta rahoittaa itse sosiaali- ja terveyspalvelunsa. Yle-veron sijaan peritään ${h.eur(h.P.vero.ahvenanmaa_mediamaksu.maara)} mediamaksu. Siksi Maarianhaminassa ${h.eur(3500)} palkasta jää noin ${h.eur(MH.netto / 12)} kuussa, enemmän kuin Helsingissä.` },
      { q: 'Lasketaanko kirkollisvero nettopalkkaan automaattisesti?', a: `Ei, vaan valitset itse, kuulutko evankelis-luterilaiseen tai ortodoksiseen kirkkoon. Seurakunnan veroprosentti määräytyy kotikunnan mukaan: evankelis-luterilaisissa seurakunnissa se on 1,00–2,00 % ja ortodoksisissa 1,75–2,25 % vuonna 2026. Kirkollisvero lasketaan samasta verotettavasta tulosta kuin kunnallisvero, joten ${h.eur(3500)} palkalla Helsingissä se on noin ${h.eur(netto(3500, 'Helsinki', 'evl').kirkollisvero / 12)} kuussa.` },
      { q: 'Mitä palkasta pidätetään verojen lisäksi?', a: `Työnantaja pidättää verokortin prosentin lisäksi työntekijän työeläkemaksun ${h.num(h.P.vero.tyoelakemaksu_prosentti, 2)} % kaikilta 17–69-vuotiailta ja työttömyysvakuutusmaksun ${h.num(h.P.vero.tyottomyysvakuutusmaksu_prosentti, 2)} % 18–64-vuotiailta, yhteensä ${h.num(h.P.vero.tyoelakemaksu_prosentti + h.P.vero.tyottomyysvakuutusmaksu_prosentti, 2)} %. Ne vähennetään verotuksessa tulosta, joten ne pienentävät hieman maksettavaa veroa. Ammattiliiton jäsenmaksu peritään usein palkasta myös, jos olet antanut siihen luvan.` },
      { q: 'Onko laskurin veroprosentti sama kuin verokortissani?', a: `Se on lähellä, jos tulosi ja vähennyksesi ovat samat kuin Verohallinnon tiedoissa. Verohallinto laskee verokortin edellisen vuoden verotuksesta, korottaa palkkatuloja ${h.num(h.P.vero.palkkatulon_korotus_ennakonpidatyksessa_prosentti, 1)} % ja pyöristää prosentin ylöspäin puoleen prosenttiyksikköön. Laskuri tekee saman pyöristyksen annetulle vuositulolle. Jos arviosi poikkeaa verokortista paljon, tilaa muutosverokortti OmaVerossa.` },
      { q: 'Mistä kuntien veroprosentit tulevat ja milloin ne päivitetään?', a: `Kunnat ilmoittavat tuloveroprosenttinsa marraskuussa, ja Verohallinto vahvistaa luettelon päätöksellään. Vuoden 2026 luettelo on annettu 18.11.2025 (VH/6585/00.01.00/2025) ja kattaa ${KUNTIA} kuntaa, joista ${AHVENANMAAN_KUNTIA} on Ahvenanmaalla. Päivitämme taulukon joka vuosi heti päätöksen jälkeen; prosentit eivät muutu kesken vuoden.` },
    ],
    body: (h) => `
<h2>Miksi kotikunta muuttaa nettopalkkaa näin paljon</h2>
<p>Hyvinvointialueuudistuksen jälkeen kunnat perivät vain osan entisestä verostaan, mutta erot jäivät. Vuonna 2026 matalin kunnallisvero on ${HALVIN.nimi}ssa, ${h.num(HALVIN.kunta, 2)} %, ja Manner-Suomen korkein ${KALLEIN.nimi}lla, ${h.num(KALLEIN.kunta, 2)} %. Kuuden prosenttiyksikön ero näyttää pieneltä, mutta se kohdistuu lähes koko verotettavaan tuloon. ${h.eur(3500)} kuukausipalkalla se tarkoittaa ${h.eur(-ERO * 12)} vuodessa.</p>
<p>Valtion tulovero sen sijaan on kaikille sama, ja sen asteikko alkaa ${h.num(h.P.vero.valtion_asteikko[0].prosentti, 2)} prosentista ensimmäisestä eurosta. Pieni- ja keskituloisella työtulovähennys syö valtionveron lähes kokonaan: vähennys on ${h.num(h.P.vero.tyotulovahennys.prosentti, 0)} % palkasta, enintään ${h.eur(h.P.vero.tyotulovahennys.enimmaismaara)}, ja se pienenee vasta, kun puhdas ansiotulo ylittää ${h.eur(h.P.vero.tyotulovahennys.pienenemisraja)}. Siksi kunnallisvero on monelle palkansaajalle suurin yksittäinen vero, ja juuri se jää yleisistä palkkalaskureista pois, kun ne käyttävät koko maan keskiarvoa.</p>
<p>Tämä laskuri ottaa kunnallisveron jokaisen kunnan omasta prosentista. Kun valitset kotikunnan, sama kunta määrää myös seurakunnan veron, jos kuulut kirkkoon, ja Ahvenanmaalla koko veromallin, joka poikkeaa mantereesta.</p>
<h2>Mitä vuonna 2026 muuttui palkan verotuksessa</h2>
<p>Valtion tuloveroasteikossa on viisi porrasta. Rajat ovat ${h.eur(h.P.vero.valtion_asteikko[1].alaraja)}, ${h.eur(h.P.vero.valtion_asteikko[2].alaraja)}, ${h.eur(h.P.vero.valtion_asteikko[3].alaraja)} ja ${h.eur(h.P.vero.valtion_asteikko[4].alaraja)}, ja ylin marginaaliprosentti on ${h.num(h.P.vero.valtion_asteikko[4].prosentti, 2)} %. Työtulovähennyksen enimmäismäärä nousi ${h.eur(h.P.vero.tyotulovahennys.enimmaismaara)}:on, ja sen pieneneminen alkaa ${h.eur(h.P.vero.tyotulovahennys.pienenemisraja)} puhtaasta ansiotulosta ja päättyy ${h.eur(h.P.vero.tyotulovahennys.pienenemisen_ylaraja)}:oon. Sen yli vähennys ei enää pienene, mikä on uutta.</p>
<p>Työntekijän työeläkemaksu on ${h.num(h.P.vero.tyoelakemaksu_prosentti, 2)} % kaikenikäisille: vuoden 2025 korkeampi maksu 53–62-vuotiaille poistui. Työttömyysvakuutusmaksu on ${h.num(h.P.vero.tyottomyysvakuutusmaksu_prosentti, 2)} %. Päivärahamaksua ${h.num(h.P.vero.paivarahamaksu_prosentti, 2)} % peritään, kun vuosiansiot ovat vähintään ${h.eur(h.P.vero.paivarahamaksu_tuloraja)}. Kunnallisverotuksen ansiotulovähennys poistettiin jo vuonna 2025, joten pienituloisen verotus nojaa nyt perusvähennykseen (${h.eur(h.P.vero.perusvahennys.enimmaismaara)}) ja työtulovähennykseen.</p>
<h2>Palkan lisäksi: eläke, Kelan tuet ja vähennykset</h2>
<p>Sama veromoottori laskee myös eläkkeen ja etuuksien verot. ${h.a('elakelaskuri', 'Eläkelaskuri')} arvioi työeläkkeesi syntymävuoden eläkeiällä ja elinaikakertoimella ja lisää Kelan kansaneläkkeen ja takuueläkkeen, jos niihin on oikeus, ja näyttää lopuksi eläkkeen netto kotikuntasi verolla. ${h.a('asumistuki-laskuri', 'Asumistukilaskuri')} kertoo, kuuluuko kuntasi asumistuen kuntaryhmään I, II vai III ja kuinka suuret asumismenot Kela hyväksyy. ${h.a('ansiosidonnainen-laskuri', 'Ansiosidonnaisen päivärahan laskuri')} näyttää porrastetut tasot, ja ${h.a('kotitalousvahennys-laskuri', 'kotitalousvähennyslaskuri')} vertaa voimassa olevaa lakia hallituksen esitykseen.</p>
<p>Laskurit toimivat vain selaimessasi: syöttämäsi palkka ei lähde mihinkään. Jokaisen luvun lähde on ${h.a('method', 'laskentatapa-sivulla')}, ja sivuston tekijästä kerrotaan ${h.a('about', 'tietoa-sivulla')}.</p>`,
  },
  en: {
    title: 'Net Salary Finland 2026: Take-Home Pay by Municipality',
    description: 'Net salary Finland 2026 with your own municipality’s real tax rate: state tax scale, municipal tax for all 308 municipalities, church tax, pension and Yle tax.',
    h1: 'Net salary in Finland 2026, by municipality',
    intro: 'Your take-home pay under the 2026 tax rules, using the actual municipal tax rate of the place you live, in English.',
    resume: (h) => `On a gross salary of ${h.eur(3500)} a month, someone living in Helsinki keeps on average ${h.eur(HKI.netto / 12)} a month in 2026, while the same salary in ${KALLEIN.nimi} leaves ${h.eur(POM.netto / 12)}. The ${h.eur(-ERO)} monthly gap comes entirely from municipal tax: ${h.num(hkiK.kunta, 2)}% in Helsinki against ${h.num(KALLEIN.kunta, 2)}% in ${KALLEIN.nimi}, with a median of ${h.num(MEDIAANI, 2)}% across all ${KUNTIA} municipalities. Everything else is the same everywhere: the progressive state income tax, reduced first by the earned income tax credit (up to ${h.eur(h.P.vero.tyotulovahennys.enimmaismaara)}), a health care contribution of ${h.num(h.P.vero.sairaanhoitomaksu_palkka_prosentti, 2)}%, a daily allowance contribution of ${h.num(h.P.vero.paivarahamaksu_prosentti, 2)}%, the Yle public broadcasting tax capped at ${h.eur(h.P.vero.yle.enimmaismaara)}, plus your own pension contribution of ${h.num(h.P.vero.tyoelakemaksu_prosentti, 2)}% and unemployment insurance of ${h.num(h.P.vero.tyottomyysvakuutusmaksu_prosentti, 2)}%. Church members also pay parish tax. The calculator uses the municipal and parish rates confirmed by Vero, the Finnish Tax Administration, on 18 November 2025 and the 2026 state tax scale, and it reproduces to the cent the ${VERO_ESIMERKKEJA} sample tax amounts Vero publishes for wages, benefits and pensions.`,
    faqs: (h) => [
      { q: 'How much of a €3,500 monthly salary do I take home in Finland in 2026?', a: `In Helsinki, without church tax, about ${h.eur(HKI.netto / 12)} a month; in Tampere ${h.eur(TRE.netto / 12)}; in ${KALLEIN.nimi} ${h.eur(POM.netto / 12)}. These are the real annual net figures divided by twelve. Your tax card rounds the withholding rate up to the next half point, so monthly payslips can show slightly less, and the difference returns as a tax refund the following year.` },
      { q: 'Why is take-home pay higher in Åland despite its high municipal tax?', a: `Åland municipalities charge ${h.num(mhK.kunta, 2)}% to 19.70% municipal tax, but the state tax percentages there are cut by ${h.num(h.P.vero.ahvenanmaa_asteikon_alennus_prosenttiyksikkoa, 2)} points because the province runs its own health and social services. Instead of the Yle tax there is a flat ${h.eur(h.P.vero.ahvenanmaa_mediamaksu.maara)} media fee. A ${h.eur(3500)} salary in Mariehamn (Maarianhamina) therefore leaves about ${h.eur(MH.netto / 12)} a month, more than in Helsinki.` },
      { q: 'Do foreigners working in Finland pay church tax?', a: `Only if you have joined the Evangelical Lutheran or Orthodox Church of Finland; nationality plays no role. Most people moving here are not members and pay no parish tax. If you are a member, the rate depends on your municipality: 1.00% to 2.00% for Lutheran parishes and 1.75% to 2.25% for Orthodox ones in 2026, charged on the same taxable income as municipal tax.` },
      { q: 'What else is taken from a Finnish payslip besides tax?', a: `Your employer withholds the employee pension contribution (TyEL) of ${h.num(h.P.vero.tyoelakemaksu_prosentti, 2)}% for everyone aged 17 to 69 and the unemployment insurance contribution of ${h.num(h.P.vero.tyottomyysvakuutusmaksu_prosentti, 2)}% for ages 18 to 64, together ${h.num(h.P.vero.tyoelakemaksu_prosentti + h.P.vero.tyottomyysvakuutusmaksu_prosentti, 2)}%. Both are deductible, so they slightly reduce your income tax. Union fees are often deducted too if you authorised it.` },
      { q: 'Is this the same percentage as on my Finnish tax card?', a: `Close to it, if your income and deductions match what Vero holds. Vero builds the tax card (verokortti) from your last assessment, raises past wages by ${h.num(h.P.vero.palkkatulon_korotus_ennakonpidatyksessa_prosentti, 1)}% and rounds the rate up to the next half point. The calculator applies the same rounding to the income you enter. If your estimate differs a lot, order a revised tax card in MyTax (OmaVero).` },
      { q: 'Where do the municipal tax rates come from?', a: `Municipalities announce their income tax rates each November and Vero confirms the list by decision. The 2026 list was issued on 18 November 2025 (VH/6585/00.01.00/2025) and covers ${KUNTIA} municipalities, ${AHVENANMAAN_KUNTIA} of them in Åland. We update the table every year right after that decision; rates never change during the year.` },
    ],
    body: (h) => `
<h2>Why your municipality changes your take-home pay</h2>
<p>Since the 2023 wellbeing services reform, Finnish municipalities levy only part of their former tax, yet the differences between them remain. In 2026 the lowest rate is ${h.num(HALVIN.kunta, 2)}% in ${HALVIN.nimi} (Grankulla), a small town next to Espoo, and the highest on the mainland is ${h.num(KALLEIN.kunta, 2)}% in ${KALLEIN.nimi}. A gap of six points sounds modest until you remember it applies to almost all of your taxable income: on ${h.eur(3500)} a month it is ${h.eur(-ERO * 12)} a year.</p>
<p>State income tax, by contrast, is identical everywhere and starts at ${h.num(h.P.vero.valtion_asteikko[0].prosentti, 2)}% from the first euro. For low and middle incomes the earned income tax credit (työtulovähennys) wipes out most of it: ${h.num(h.P.vero.tyotulovahennys.prosentti, 0)}% of your pay, at most ${h.eur(h.P.vero.tyotulovahennys.enimmaismaara)}, shrinking only once net earned income passes ${h.eur(h.P.vero.tyotulovahennys.pienenemisraja)}. That is why municipal tax is the largest single tax for many employees, and why calculators using a national average can be off by a hundred euros a month.</p>
<p>If you are comparing job offers in Helsinki, Espoo and Tampere, or deciding which side of a municipal border to rent on, use the municipality list below or the ${h.a('kuntavertailu', 'full municipality comparison')}. Vero applies the rate of your home municipality for the tax year to the whole year’s income.</p>
<h2>What changed for 2026</h2>
<p>The state scale has five brackets with thresholds at ${h.eur(h.P.vero.valtion_asteikko[1].alaraja)}, ${h.eur(h.P.vero.valtion_asteikko[2].alaraja)}, ${h.eur(h.P.vero.valtion_asteikko[3].alaraja)} and ${h.eur(h.P.vero.valtion_asteikko[4].alaraja)}, and a top marginal rate of ${h.num(h.P.vero.valtion_asteikko[4].prosentti, 2)}%. The earned income credit rose to ${h.eur(h.P.vero.tyotulovahennys.enimmaismaara)} and now stops shrinking at ${h.eur(h.P.vero.tyotulovahennys.pienenemisen_ylaraja)} of net income, so even high earners keep part of it.</p>
<p>The employee pension contribution is a flat ${h.num(h.P.vero.tyoelakemaksu_prosentti, 2)}% for all ages: the higher 2025 rate for people aged 53 to 62 is gone. Unemployment insurance is ${h.num(h.P.vero.tyottomyysvakuutusmaksu_prosentti, 2)}%. The ${h.num(h.P.vero.paivarahamaksu_prosentti, 2)}% daily allowance contribution applies once annual earnings reach ${h.eur(h.P.vero.paivarahamaksu_tuloraja)}.</p>
<h2>Beyond salary: pension, Kela and deductions</h2>
<p>The same tax engine handles pensions and benefits. The ${h.a('elakelaskuri', 'pension calculator')} estimates your earnings-related pension with the retirement age for your year of birth and the life expectancy coefficient, adds Kela’s national and guarantee pensions where they apply, and shows the net amount after your municipality’s tax. The ${h.a('asumistuki-laskuri', 'housing allowance calculator')} tells you which Kela municipality group you fall in. The ${h.a('ansiosidonnainen-laskuri', 'unemployment allowance calculator')} shows the step-downs, and the ${h.a('kotitalousvahennys-laskuri', 'household tax credit calculator')} compares current law with the government proposal.</p>
<p>All calculators run in your browser; the salary you type never leaves it. The source of every figure is listed on the ${h.a('method', 'calculation method page')}, and the ${h.a('about', 'about page')} explains who publishes the site.</p>`,
  },
};
